const mongoose = require('mongoose');

const MonthlyDataSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  month: {
    type: String, // Format: "Jan 2023"
    required: [true, 'Please provide a month identifier']
  },
  year: {
    type: Number,
    required: [true, 'Please provide a year']
  },
  monthNum: {
    type: Number, // 0-11 for Jan-Dec
    required: [true, 'Please provide a month number']
  },
  income: {
    type: Number,
    required: [true, 'Please provide income amount'],
    default: 0
  },
  expenses: {
    type: Number,
    required: [true, 'Please provide expenses amount'],
    default: 0
  },
  savings: {
    type: Number,
    default: 0
  },
  // Category breakdown
  categorySpending: [{
    category: {
      type: String,
      required: true
    },
    amount: {
      type: Number,
      required: true,
      default: 0
    },
    budget: {
      type: Number,
      default: 0
    }
  }],
  // Net worth tracking
  netWorth: {
    type: Number,
    default: 0
  },
  // If this record was auto-generated from transactions
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  notes: {
    type: String,
    maxlength: [300, 'Notes cannot be more than 300 characters']
  },
  createdAt: {
    type: Date,
    default: Date.now
  }
});

// Create compound index for uniqueness per user and month/year
MonthlyDataSchema.index({ user: 1, year: 1, monthNum: 1 }, { unique: true });

module.exports = mongoose.model('MonthlyData', MonthlyDataSchema); 